server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/auth/**
        - id: loan-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/loans/**

jwt:
  secret: loan-origination-secret-key-must-be-at-least-256-bits-long-for-hs256
